services:
  mysql:
    image: mysql:8.4
    container_name: lab-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab_persistencia
    ports:
      - "3307:3306"
    volumes:
      - mysql_lab_data:/var/lib/mysql

volumes:
  mysql_lab_data:
